name: check

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
      GITHUB_USERNAME: ${{ github.repository_owner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Install Node.js dependencies
        run: npm install

      - name: Validate commit messages
        run: npx commitlint --from=origin/main --to=HEAD --verbose --config .config/.commitlintrc.json

      - name: Format .NET code
        run: dotnet format --verify-no-changes --verbosity detailed --severity info

      - name: Run CSharpier
        run: dotnet csharpier . --check --loglevel debug

      - name: Run Prettier
        run: npx prettier "**/*.{json,yaml}" --check --log-level debug

      - name: Run Markdownlint
        run: npx markdownlint . --dot --ignore node_modules --ignore packages --ignore CHANGELOG.md --disable MD013

      - name: Run CSpell
        run: npx cspell "**/*.{md,txt,json,yaml,cs}" --config .config/cspell.json

      - name: Build .NET
        run: dotnet build

      - name: Test .NET
        run: dotnet test

  check-windows:
    runs-on: windows-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Verify CER file
        run: |
          $cerFilePath = ".\msix\cert\SpeechToTextCli.cer"
          if (Test-Path $cerFilePath) {
            Write-Output "CER file found at $cerFilePath"
            try {
              $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($cerFilePath)
              Write-Output "CER file is valid and ready for packaging."
            } catch {
              Write-Error "CER file is corrupted or invalid. Error details: $_"
            }
          } else {
            Write-Error "CER file is missing."
          }
        shell: pwsh

      - name: Build VCXProj
        run: msbuild src/SpeechToTextContextMenu/SpeechToTextContextMenu.vcxproj /p:Configuration=Release
